import {
  AlertTriangle,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUpDown,
  ArrowUpFromLine,
  BarChart3,
  Boxes,
  CalendarDays,
  Box,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  Copy,
  Download,
  Eye,
  FileText,
  Filter,
  FolderTree,
  Grid3x3,
  HelpCircle,
  History,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lock,
  LogOut,
  type LucideIcon,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  Move,
  Package,
  PackageOpen,
  Footprints,
  Pencil,
  Plus,
  RefreshCw,
  RotateCw,
  Ruler,
  Scan,
  ScanBarcode,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Trash2,
  Redo2,
  Truck,
  Undo2,
  User,
  Users,
  Warehouse,
  X,
  XCircle,
} from "lucide-react";

export const ICON_MAP = {
  dashboard: LayoutDashboard,
  movements: ArrowLeftRight,
  entrada: ArrowDownToLine,
  salida: ArrowUpFromLine,
  traslado: Move,
  ajuste: SlidersHorizontal,
  inventario: ClipboardList,
  alerta: AlertTriangle,
  stock: Package,
  producto: Boxes,
  caja: PackageOpen,
  lote: Layers,
  almacen: Warehouse,
  zona: LayoutGrid,
  ubicacion: MapPin,
  proveedor: Truck,
  cliente: Users,
  usuario: User,
  rol: Shield,
  categoria: FolderTree,
  uom: Ruler,
  comentario: MessageSquare,
  historial: History,
  buscar: Search,
  filtrar: Filter,
  ordenar: ArrowUpDown,
  ver: Eye,
  editar: Pencil,
  eliminar: Trash2,
  aprobar: CheckCircle2,
  anular: XCircle,
  cerrar: Lock,
  exportar: Download,
  agregar: Plus,
  atras: ArrowLeft,
  refrescar: RefreshCw,
  calendario: CalendarDays,
  nota: FileText,
  codigoBarras: ScanBarcode,
  configuracion: Settings,
  reportes: BarChart3,
  cerrarSesion: LogOut,
  ayuda: HelpCircle,
  menu: Menu,
  chevronDown: ChevronDown,
  cerrarPanel: X,
  subir: ChevronUp,
  bajar: ChevronDown,
  pantallaCompleta: Maximize2,
  salirPantallaCompleta: Minimize2,
  cuadricula: Grid3x3,
  encuadrar: Scan,
  /** Rotar 90° (modo construcción del mapa; RotateCw de Lucide, §6.13). */
  rotar: RotateCw,
  /** Deshacer/Rehacer cambios del mapa (Undo2/Redo2 de Lucide, §6.13). */
  deshacer: Undo2,
  rehacer: Redo2,
  /** Duplicar elemento del mapa (Copy de Lucide, §6.13). */
  duplicar: Copy,
  /** Vista de alambre/wireframe del 3D (Box de Lucide, §6.13). */
  alambre: Box,
  /** Modo caminar del 3D (Footprints de Lucide, §6.13). */
  caminar: Footprints,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;

export interface IconProps {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
  "aria-label"?: string;
}

export function Icon({ name, size = 16, strokeWidth, className, ...rest }: IconProps) {
  const LucideIcon = ICON_MAP[name];
  return <LucideIcon size={size} strokeWidth={strokeWidth} className={className} {...rest} />;
}
